spring:
# Redis
 redis:
  host: localhost
  port: 6379
  password: #123456
  database: 0
  timeout: 100  # 单位毫秒
  jedis:
   pool:
    max-active: 10
    max-wait: 10
    max-idle: 10
    min-idle: 10
 # 数据库
 datasource:
  url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
  username: root
  password: root 
  driver-class-name: com.mysql.cj.jdbc.Driver   
# JPA 
 jpa: 
  show-sql: true
  database-platform: com.caowei.config.MySQLConfig  # 使用的方言
  hibernate:
   ddl-auto: update  # 配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
   